"""Add resources

Revision ID: 8b3f73d9bd58
Revises: c55d02f89b01
Create Date: 2026-01-02 13:39:16.438368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3f73d9bd58'
down_revision = 'c55d02f89b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Text(), nullable=False),
    sa.Column('passwd', sa.Text(), server_default=sa.text(u"('')"), nullable=False),
    sa.Column('surname', sa.Text(), nullable=False),
    sa.Column('forename', sa.Text(), nullable=False),
    sa.Column('telno', sa.Text(), nullable=False),
    sa.Column('addr1', sa.Text(), nullable=True),
    sa.Column('addr2', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('postcode', sa.Text(), nullable=True),
    sa.Column('active', sa.CHAR(length=1), server_default=sa.text(u"'Y'"), nullable=False),
    sa.Column('admin', sa.CHAR(length=1), server_default=sa.text(u"'N'"), nullable=False),
    sa.CheckConstraint(u"active in ('Y', 'N')"),
    sa.CheckConstraint(u"admin in ('Y', 'N')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid')
    )
    op.create_table('user_resources',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'resource_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_resources')
    op.drop_table('users')
    op.drop_table('resources')
    # ### end Alembic commands ###
